version: '3.7'

services:
  plccoms-mqtt-bridge:
    image: ocervinka/plccoms-mqtt-bridge
    restart: always
    volumes:
      - ./plccoms-mqtt-bridge/config.yaml:/etc/plccoms-mqtt-bridge/config.yaml
    networks:
      - ha-network

networks:
  ha-network:
    driver: bridge
